import api from './axiosInstance';

export const confidasApi = {
  getKpis:                  () => api.get('/confidas/kpis'),
  getPaymentHistory:        () => api.get('/confidas/payment-history'),
  getPaymentHistoryFull:    () => api.get('/confidas/payment-history-full'),
  getChargesVsPayments:     () => api.get('/confidas/charges-vs-payments'),
  getChargesVsPaymentsFull: () => api.get('/confidas/charges-vs-payments-full'),
  getCcrHistory:            () => api.get('/confidas/ccr-history'),
  getArPie:                 () => api.get('/confidas/ar-pie'),
  getArDonut:               () => api.get('/confidas/ar-donut'),
  getTotalCharges:          () => api.get('/confidas/total-charges'),
  getTotalChargesFull:      () => api.get('/confidas/total-charges-full'),
  getAdjustments:           () => api.get('/confidas/adjustments'),
  getAdjustmentsFull:       () => api.get('/confidas/adjustments-full'),
  getDenialReasons:         () => api.get('/confidas/denial-reasons'),
  getProductionDosChart:         () => api.get('/confidas/production/dos-chart'),
  getProductionDosReimbursement: () => api.get('/confidas/production/dos-reimbursement'),
  getProductionDoeChart:         () => api.get('/confidas/production/doe-chart'),
  getProductionDoeReimbursement: () => api.get('/confidas/production/doe-reimbursement'),
  getProductionDodPaymentMethod: () => api.get('/confidas/production/dod-payment-method'),
  getProductionDodReimbursement: () => api.get('/confidas/production/dod-reimbursement'),
  getBankDeposits:          () => api.get('/confidas/bank-deposits'),
  getDepositsByProvider:    (month = null) => api.get('/confidas/deposits-by-provider', { params: month ? { month } : {} }),
  // Facility
  getFacilityDosLast12:    (month) => api.get('/confidas/facility/dos/last12',    { params: month && month !== 'all' ? { month } : {} }),
  getFacilityDosLastMonth: ()      => api.get('/confidas/facility/dos/lastmonth'),
  getFacilityDoeLast12:    (month) => api.get('/confidas/facility/doe/last12',    { params: month && month !== 'all' ? { month } : {} }),
  getFacilityDoeLastMonth: ()      => api.get('/confidas/facility/doe/lastmonth'),
  getFacilityDodLast12:    (month) => api.get('/confidas/facility/dod/last12',    { params: month && month !== 'all' ? { month } : {} }),
  getFacilityDodLastMonth: ()      => api.get('/confidas/facility/dod/lastmonth'),
  // AR Page  — mode, bucket, carrier, financial are optional filter params
  getArBar:       (mode, bucket, carrier, financial) => api.get('/confidas/ar/bar',       { params: { mode, ...(bucket    ? { bucket }    : {}), ...(carrier   ? { carrier }   : {}), ...(financial ? { financial } : {}) } }),
  getArPieChart:  (mode, bucket, carrier, financial) => api.get('/confidas/ar/pie-chart', { params: { mode, ...(bucket    ? { bucket }    : {}), ...(carrier   ? { carrier }   : {}), ...(financial ? { financial } : {}) } }),
  getArCarrier:   (mode, bucket, carrier, financial) => api.get('/confidas/ar/carrier',   { params: { mode, ...(bucket    ? { bucket }    : {}), ...(carrier   ? { carrier }   : {}), ...(financial ? { financial } : {}) } }),
  getArFinancial: (mode, bucket, carrier, financial) => api.get('/confidas/ar/financial', { params: { mode, ...(bucket    ? { bucket }    : {}), ...(carrier   ? { carrier }   : {}), ...(financial ? { financial } : {}) } }),
  // Insight
  getInsightDosLast12:    (groupBy, filter) => api.get('/confidas/insight/dos/last12',    { params: { groupBy, ...(filter && filter !== 'all' ? { filter } : {}) } }),
  getInsightDosLastMonth: (groupBy, filter) => api.get('/confidas/insight/dos/lastmonth', { params: { groupBy, ...(filter && filter !== 'all' ? { filter } : {}) } }),
  getInsightDosFilters:   (groupBy)         => api.get('/confidas/insight/dos/filters',   { params: { groupBy } }),
  getInsightDoeLast12:    (groupBy, filter) => api.get('/confidas/insight/doe/last12',    { params: { groupBy, ...(filter && filter !== 'all' ? { filter } : {}) } }),
  getInsightDoeLastMonth: (groupBy, filter) => api.get('/confidas/insight/doe/lastmonth', { params: { groupBy, ...(filter && filter !== 'all' ? { filter } : {}) } }),
  getInsightDoeFilters:   (groupBy)         => api.get('/confidas/insight/doe/filters',   { params: { groupBy } }),
  getInsightDodLast12:    (groupBy, filter) => api.get('/confidas/insight/dod/last12',    { params: { groupBy, ...(filter && filter !== 'all' ? { filter } : {}) } }),
  getInsightDodLastMonth: (groupBy, filter) => api.get('/confidas/insight/dod/lastmonth', { params: { groupBy, ...(filter && filter !== 'all' ? { filter } : {}) } }),
  getInsightDodFilters:   (groupBy)         => api.get('/confidas/insight/dod/filters',   { params: { groupBy } }),
};
